outputFigPath='C:\Users\xjm9\OneDrive - CDC\JonoRobyn_PrEPART\PCE_and_Sobol_Analysis\';

figLabels={...
    'B_PrEP',...
    'H_PrEP',...
    'B_1to2',...
    'H_1to2',...
    'B_2to3_atDiag',...
    'H_2to3_atDiag',...
    'B_2to3_afterDiag',...
    'H_2to3_afterDiag',...
    'B_3to4',...
    'H_3to4',...
    'B_4to3',...
    'H_4to3',...
    'B_4to5',...
    'H_4to5',...
    'B_5to4',...
    'H_5to4',...
};


for kk=1:16

    idx_dx=kk;
    evaluate_PolyChaos;

    saveas(gcf, strcat(outputFigPath,figLabels{kk},'.png'),'png');

    close all
end
