%This quick script generates an excel spreadsheet aggregating our data

filePrefix='Tot_Sob_g';
fileSuffix='_AllP.mat';
filePrefixPrincipal='Sob_g';


outputPath='./Spreadsheet_Outputs/SobolResults.xls';

sheetNames={...
    'IncidenceBlackAA',...
    'IncidenceHispLat',...
    'IRRBlackAA',...
    'IRRHispLat'
};

variableNames={...
    'Year',...
    'BlackAA_PrEP',...
    'HispLat_PrEP',...
    'BlackAA_1to2',...
    'HispLat_1to2',...
    'BlackAA_2to3_atDiag',...
    'HispLat_2to3_atDiag',...
    'BlackAA_2to3_afterDiag',...
    'HispLat_2to3_afterDiag',...
    'BlackAA_3to4',...
    'HispLat_3to4',...
    'BlackAA_4to3',...
    'HispLat_4to3',...
    'BlackAA_4to5',...
    'HispLat_4to5',...
    'BlackAA_5to4',...
    'HispLat_5to4'
};

yrArray=(2023:1:2034)';


for i=1:4

    load(strcat(filePrefix,num2str(1),fileSuffix));
    sobTable=eval(strcat(filePrefix,num2str(1),'_All'));
    sobTable=[yrArray sobTable'];
    sobTable=array2table(sobTable,"VariableNames",variableNames);

    fprintf('Writing table... ');    
    writetable(sobTable,outputPath,'Sheet',strcat(sheetNames{i},'_TotalIndex'));
    fprintf('done.\n ');


    load(strcat(filePrefixPrincipal,num2str(1),fileSuffix));
    sobTable=eval(strcat(filePrefixPrincipal,num2str(1),'_All'));
    sobTable=[yrArray sobTable'];
    sobTable=array2table(sobTable,"VariableNames",variableNames);
    fprintf('Writing table... ');    
    writetable(sobTable,outputPath,'Sheet',strcat(sheetNames{i},'_PrincipalIndex'));
    fprintf('done.\n ');


end

